### ISSUE TITLE
Any example for static content serving

### ISSUE THREAD

**Issue by ygl-rg** [sisk-http/core#1]
Hi

   I noticed the introduction mentions about one of the purposes of using sisk is for file server. I want to know whether there is any example for how to serve static files. I want to use it to host my vue app.

Regards

gelin yan

**Comment by CypherPotato** [comment]
Hello.

We had an example on the old website, but it has been removed with the new one. We are working on a new quickstarter repo with lots of examples, some with UI templates, some with modules, etc.

In [this link](https://github.com/sisk-http/docs/blob/594fa427ceee5766a482edbf53ee3d5328bd94e2/static/view/docs/examples.html#L93C24-L93C24) to an old version of the documentation repository you can find a very simple example of serving files.

You will need to extend a route to serve directory listings if you want one. It's a very primitive example of how you can work with this.

Thank you.

**Comment by ygl-rg** [comment]
thanks
