### ISSUE TITLE
Missing .NET 9 Targets for MAUI (Android, iOS, etc.)

### ISSUE THREAD

**Issue by Sascha-L** [sisk-http/core#15]
Hi,

you added .NET 9 support but the nuget packages does not include the framework targets for Android, iOS, MacOS, etc.

See screenshot:

![image](https://github.com/user-attachments/assets/d7203885-a0f8-4a53-8246-b0cedeb9c5d1)

**Comment by CypherPotato** [comment]
Are you sure about that? I mean, have you tried to run Sisk within an Android app?

I don't know if Microsoft changed things with .NET 9, but it should be compatible with anything which runs on it.

**Comment by Sascha-L** [comment]
I'm sorry, you can delete this issue. Something changed with .NET9 or Visual Studio 17.12 and I thought the reason why my assembly was not loaded, was the missing platforms of your nuget package, but everything is still fine with your nuget package. Keep up the good work! :-)

**Comment by CypherPotato** [comment]
I'm glad it worked for you. Feel free to open another issue if you face any other problems.
